### PR TITLE
Resource and Course Page

### PR DESCRIPTION
**Pull request by AMMAR-62**

### CODE REVIEW

**Comment by AMMAR-62** [comment]
Capture1
@Classes
Capture2
@Resources

**Comment by AMMAR-62** [comment]
Some Changes made in  the UI


Classes Page



Resources Page

**Comment by AMMAR-62** [comment]
Please Suggest some background edits for the Resource Page... cause white is not suiting the background and when try to change it, it looks ugly

**Review by ShubhankarKG — CHANGES_REQUESTED** [review]
It looks as if you have commited some files where there were merge conflicts. In its current state, the /client folder will not start up. Please make the relevant changes and push this branch again.

**Comment by AMMAR-62** [comment]
Closing this Pull Request ... Please see resolved conflicts on other PR

**Pull request closed without merging**
