### PR TITLE
Added the Image animation on Landing Page and updated the footer

### PR DESCRIPTION
**Pull request by Tejas2909**

### CODE REVIEW

**Review by pal-16 — APPROVED** [review]

**Comment by thedarkdivinity** [comment]
ye merge nhi hua???

**Comment by pal-16** [comment]
this will be merged once we get the final client images

**Comment by pal-16** [comment]
Hi @BhavyaSheth22  Reminder to merge this as and when possible for you

**Comment by BhavyaSheth22** [comment]
Hi @Tejas2909, thanks for this! Can you please add a margin or padding around the images at the top and bottom? Right now, it is sticking to the navbar.

**Pull request merged**
